### ISSUE TITLE
Alternate name for the project?

### ISSUE THREAD

**Issue by kohlmannj** [cssinjs/aphrodite-jss#8]
Hi,

Please don't take this the wrong way: as clever as "Aphrodisiac" is, the name is awkward at best. In particular, can be offputting to others when explaining the tool and its benefits. It's hard to credibly demonstrate this when the name is such a deterrent. (Yes, this actually happened in a meeting!)

May I suggest "Venus", the Roman goddess of love, or Aphrodite's counterpart? Thanks for your consideration.

**Comment by kof** [comment]
Hi, what exactly is offputting about this name, maybe I don't know something?

**Comment by kohlmannj** [comment]
Hi @kof, thanks for the reply. In a meeting when I introduced a project's usage of Aphrodisiac, most of my coworkers (an equal mix of men and women) were taken aback by the name. The definition of "aphrodisiac" as an object that stimulates sexual desire and arousal seem to have been the source of that! 😅

I don't consider my coworkers either lewd or prude, but in practical terms, the name distracted from an honest effort to introduce a new, better tool to the team.

All things considered, I get the desire to associate the project with Aphrodite (and for good reason: that's how I found it). The sexual connotation of "aphrodisiac", though, might send the wrong message for newcomers? Anyway, I hope this explanation helps shed some light.

**Comment by kof** [comment]
Its probably the differences in the mentality.  Wikipedia definition of aphrodisiac doesn't sound negative to me. In fact, humans sexuality is one of the reasons that makes humans what we are and allows our population to grow.

The theory behind the name of this project is that aphrodisiac makes the JSS api sexier in aphrodite's way. Of course it isn't meant literally.

>  were taken aback by the name

What does this mean? Did they feel ashamed or embarrassed? Or were they  just insecure about how to behave because of what the co-workers would think of them?

When I watch american TV I see sex everywhere. Look at the music videos, they are all about sex.

I don't understand how all this gets along with such a prude mentality where a single word "aphrodisiac" makes them feel awkward.

**Comment by kof** [comment]
Also why "Aphrodite" the Greek goddess of love, beauty, pleasure, and procreation doesn't make them feel awkward, but "Aphrodisiac" does? What exactly is the difference there?

**Comment by ai** [comment]
I will support @kof in his opinion. After sexual revolution of 60’s our society is based on idea, that sexuality could not hurt anyone.

Technically, it was not a problem even before 60’s. Most of classic paintings contain nude people and sexual context.

@kohlmannj maybe if we will find what exactly make them awkward, we could fix it in better way?

**Comment by sergey-lapin** [comment]
Github threads are soooo educative nowadays 😄

**Comment by kof** [comment]
I am really just trying to understand whats going on.

**Comment by sergey-lapin** [comment]
@kohlmannj Actually tech people should not be discouraged to use some lib because of name(unless it is really shitty one and offensive), they should evaluate what benefit or harm it could bring to project. In modern society "aphrodisiac" is completely neutral name, whatever gender you are or race or religion. So it is weird situation that your colleagues have such reaction. Maybe they have some stereotypes. It is definitely not project maintainer responsibility, but rather yours to educate people around you. I also think that asking to change name of the project is kinda rude in this situation.

**Comment by kof** [comment]
I don't think its rude, in fact I appreciate that @kohlmannj created an issue instead of just looking for another solution.

**Comment by kof** [comment]
Right now I am investigating this phenomenon in order to understand if this is an isolated case. If it is isolated then we should educate the particular group of people, otherwise it will be simply harmful to the project and will not bring the desired result.

The opinion of masses can't be changed by simple facts, they need a revolution I don't want to lead.

**Comment by sergey-lapin** [comment]
I want to be clear, that I just said my opinion about situation, I am not maintainer, and it is totally up to @kof to decide here. I did not want to offense anybody here, but this is simply how situation looks for me.

**Comment by dmitrygusev** [comment]
I'm sorry, but will my libido increase if I fork this project? Or just watching it should be enough?

**Comment by Noiwex** [comment]
I suggest maintainer not to take this trolling into account and lock the issue/block author.

**Comment by ai** [comment]
@Noiwex I don’t think @kohlmannj is a troll. It had real problem and we should understand why.

**Comment by dmitrygusev** [comment]
@Noiwex why do you think it's a trolling?
I admit my previous comment was a trolling, but I personally understand the issue that author had raised very well.

**Comment by private-face** [comment]
I guess there will always be those who find awkward or offensive any given name except complete gibberish. For example I can say that I find name “Venus” disturbing because in Russia it has bad connotations to STDs.

Seriously though, people in this discussion have already spent much more time than is needed to make a simple decision: should you use this package as is or should you fork-and-rename it?

**Comment by iamstarkov** [comment]
@private-face i dont think you are in position to force OP to do anything

**Comment by private-face** [comment]
@iamstarkov sure, nobody is. What is your point?

**Comment by kof** [comment]
I am thinking of renaming to "aphrodite-jss". Mostly because of consistency with react-jss, styled-jss and other "on-top-of-jss" libraries.

**Comment by ai** [comment]
@kof yeap, technically `aphrodite-jss` more clear. You can understand project purpose just by name, without description.

**Comment by Noiwex** [comment]
@iamstarkov are you in charge? what's the point in your senseless callout?

**Comment by iamstarkov** [comment]
@private-face my point is that your suggestion for OP to choose either they just use this project or fork-n-rename-n-use is rude and decrease the value of OP's polite and valid question.

@Noiwex what do you mean? i wouldnt say, my callout was senseless.

**Comment by iamstarkov** [comment]
@kof i like `aphrodite-jss` suggestion

**Comment by thaylin79** [comment]
I was in that meeting and I was taken aback by how many syllables were in it! 5! I don't have time to say that! :) j/k. In reality, I don't think it was the sexual overtones that might be thought of when thinking about an aphrodisiac as much as the the play from aphrodite to aphrodisiac. Less aghast and more silliness. I mean, I don't think a single woman in our group wears a victorian corset and I stopped wearing my top hat and monocle months ago! Also, @kof, I too like the aphrodite-jss suggestion.

**Comment by kohlmannj** [comment]
@kof My thanks to you and others for taking the time to genuinely listen and understand—certainly didn't mean for this issue thread to become a circus. For what it's worth, `aphrodite-jss` would be good! Thanks again.

**Comment by kof** [comment]
So are you guys going to use it in production?

**Comment by kohlmannj** [comment]
@kof Right now we're using it in the latest version of an internal React component library. It will absolutely be used in production, public-facing builds of [paid posts](http://www.tbrandstudio.com) within a few weeks.

**Comment by kof** [comment]
nice.

**Comment by kof** [comment]
renamed and published

**Comment by kof** [comment]
I wish every one a healthy libido and a freedom to express your sexuality at work!
